# Site settings
title: CLRS读书笔记
email: m.xinerd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  CLRS读书笔记
baseurl: "/introduction-to-algorithms" # the subpath of your site, e.g. /blog
url: "http://xinerd.github.io" # the base hostname & protocol for your site
twitter_username: xinerd
github_username:  xinerd

# Build settings
markdown: kramdown
